# Generated by Django 2.0 on 2018-02-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_album_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='favorites',
            field=models.IntegerField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='song',
            name='favorites',
            field=models.IntegerField(default=0, max_length=1000),
        ),
    ]
