# Generated by Django 2.0 on 2018-02-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_favoritealbum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='song',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='song',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='song',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='song',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(default='', max_length=250),
        ),
    ]
